#ifndef CRANE_H
#define CRANE_H

#import <Foundation/Foundation.h>

#define CRANE_TASK_CHECK 1
#define CRANE_TASK_SUPPORTED_APPS 2
#define CRANE_TASK_APPS_WITH_CONTAINERS 3
#define CRANE_TASK_APP_CONTAINERS 4
#define CRANE_TASK_ACTIVE_CONTAINER 5
#define CRANE_TASK_SET_ACTIVE_CONTAINER 6
#define CRANE_TASK_CREATE_CONTAINER 7
#define CRANE_TASK_DELETE_CONTAINER 8
#define CRANE_TASK_DELETE_CONTAINER_CONTENT 9
#define CRANE_TASK_WIPE_CONTAINER 10
#define CRANE_TASK_MAKE_DEFAULT 11
#define CRANE_TASK_CONTAINER_SETTINGS 12
#define CRANE_TASK_SET_CONTAINER_SETTINGS 13
#define CRANE_TASK_LAUNCH_APP_WITH_CONTAINER 14

NSString *handleCraneTaskFromRawData(UInt8 *eventData, NSError **error);

#endif
